Fix AttributeError on _set_obs_state
When running multiple devices via MultiDeviceTestContext, it
could result in failures during initialisation like
```
AttributeError: 'SKABaseDeviceStateModel' object has no attribute '_set_obs_state'
```

Issue was caused by updates to the transitions dict class variable
instead of maintaining a unique instance per object.