REL-2051: Fix synchronisation issue with test_abort
We need to wait for the command to actually start before we call Abort,
otherwise we might get the Result supplied by the `Abort()` command when
it dequeues and discards the task, for example, for the CI:

__________________________________ test_abort __________________________________
device_under_test = ExampleMultiDevice(test/nodb/examplemultidevice)
change_event_callbacks = <ska_tango_testing.mock.tango.event_callback.MockTangoEventCallbackGroup object at 0x7efe8b4ea3b0>
    @pytest.mark.forked
    def test_abort(
        device_under_test: tango.DeviceProxy,
        change_event_callbacks: MockTangoEventCallbackGroup,
    ) -> None:
        """
        Test abort.

        :param device_under_test: a proxy to the device under test
        :param change_event_callbacks: dictionary of mock change event
            callbacks with asynchrony support
        """
        device_under_test.subscribe_event(
            "longRunningCommandResult",
            tango.EventType.CHANGE_EVENT,
            change_event_callbacks["longRunningCommandResult"],
        )
        change_event_callbacks.assert_change_event("longRunningCommandResult", ("", ""))

        # AbortingLongRunning
        result_code, command_id = device_under_test.AbortingLongRunning(0.1)
        assert ResultCode(int(result_code)) == ResultCode.QUEUED
        assert command_id.endswith("AbortingLongRunning")

        device_under_test.Abort()

        next_result = change_event_callbacks.assert_against_call("longRunningCommandResult")
        command_id, message = next_result["attribute_value"]
        assert command_id.endswith("AbortingLongRunning")
>       assert message == '"AbortingTask Aborted 0.1"'
E       assert '[7, "Command...een aborted"]' == '"AbortingTask Aborted 0.1"'
E
E         - "AbortingTask Aborted 0.1"
E         + [7, "Command has been aborted"]
tests/integration/multidevice/test_multidevice.py:147: AssertionError