Update to PyTango 9.3.1
Current docker images get PyTango 9.2.5 with cppTango 9.3.3, but
these do not work correctly together.  Tests like
`TestSKASubarray.test_ReleaseAllResources` failed with errors like:

```
 >       attr_value = self.read_attribute(name).value
583 E       AttributeError: 'DeviceAttribute' object has no attribute 'value'
```

We need a newer PyTango version to fix this.

- Update to PyTango 9.3.1
- Update to  numpy 1.17.2 to match ska-python-builder image
- `pipenv lock` was run to update the `Pipfile.lock`
- Removed unnecessary packages from `install_requires` for Python 3.7+
- Added SARAO to author and copyright notices
- Version bumped to 0.1.4